[versions]
activity = "1.10.1"
androidxMaterial = "1.7.8"
#appcompat = "1.6.1"
appcompat = "1.7.0"
coil = "2.5.0"
coilCompose = "2.5.0"
compiler = "4.15.1"
compose = "1.0.0-alpha.5"
constraintlayout = "2.2.0"
coreKtx = "1.12.0"
espressoCore = "3.5.1"
eyedropper = "1.1.0"
fragmentKtx = "1.6.2"
hiltAndroid50 = "2.50"
hiltAndroid48 = "2.48"
junit = "4.13.2"
androidxTest = "1.5.2"
junitVersion = "1.1.5"
lifecycleRuntimeCompose = "2.8.0-alpha01"
lifecycleRuntimeKtx = "2.6.0"
baselineProfiles = "1.3.1"
lifecycleViewmodelCompose = "2.8.7"
androidxMacroBenchmark = "1.2.4"
lifecycleViewmodelKtx = "2.7.0"
material = "1.12.0"
navigationFragmentKtx = "2.8.4"
opencv = "4.12.0"
sdpAndroid = "1.1.0"
uiAutomator = "2.3.0"
kotlin = "2.1.20"
ui = "1.7.8"
agp = "8.2.2"
dokka = "1.9.20"
kotlinBinaryCompatibility = "0.14.0"
jvmTarget = "11"
nexusPlugin = "0.28.0"
spotless = "6.21.0"
powerMenu = "2.2.4"
timber = "5.0.1"
constraintlayoutVersion = "2.1.4"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.8.7"
recyclerview = "1.1.0"





[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "androidxMaterial" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
compose = { module = "com.github.bumptech.glide:compose", version.ref = "compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
eyedropper = { module = "com.github.madrapps:eyedropper", version.ref = "eyedropper" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
hilt-android-compiler-v250 = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid50" }
hilt-android-v250 = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid50" }
#hilt-android-compiler-v248 = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid48" }
#hilt-android-v248 = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid48" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
opencv = { module = "org.opencv:opencv", version.ref = "opencv" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sdpAndroid" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
powermenu = { module = "com.github.skydoves:powermenu", version.ref = "powerMenu" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTest" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "baselineProfiles" }
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }




[plugins]
#kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nexus-plugin = { id = "com.vanniktech.maven.publish", version.ref = "nexusPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
baseline-profile = { id = "androidx.baselineprofile", version.ref = "androidxMacroBenchmark" }
kotlin-binary-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibility" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

#spotless-gradle = { id = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }